[tasks.watch]
command = "wrangler"
args = ["preview", "--watch"]

[tasks.publish]
command = "wrangler"
args = ["publish"]

[tasks.icons]
env = { "RUST_LOG" = "api" }
command = "cargo"
args = ["run", "--bin=site_icons", "--", "${@}"]
# watch = true
