import _ from 'lodash';

export const demoNpmPackages = _.shuffle([
  'webpack',
  'lodash',
  'chalk',
  'react',
  'express',
  'moment',
  'vue',
  'axios',
  'glob',
  '@babel/core',
  'jquery',
  'eslint',
  'dotenv',
  '@angular/core',
  'redux',
  'gulp',
  'aws-sdk',
  'mocha',
  'socket.io',
  'mongodb',
  'sass',
  'jest',
  'emotion',
  'styled-components',
  'node-fetch',
  '@webcontainer/api',
]);

export const demoRepos = _.shuffle([
  'microsoft/vscode',
  'microsoft/terminal',
  'facebook/react',
  'facebook/create-react-app',
  'vercel/next.js',
  'tailwindlabs/tailwindcss',
  'microsoft/TypeScript',
  'nodejs/node',
  'electron/electron',
  'sindresorhus/awesome',
  'vuejs/vue',
  'rails/rails',
  'angular/angular',
  'jquery/jquery',
  'gatsbyjs/gatsby',
  'airbnb/javascript',
  'golang/go',
  'grafana/grafana',
  'Homebrew/brew',
  'd3/d3',
  'tensorflow/tensorflow',
  'mui/material-ui',
  'nestjs/nest',
  'twbs/bootstrap',
  'microsoft/PowerToys',
  'ohmyzsh/ohmyzsh',
  'flutter/flutter',
  'ant-design/ant-design',
  'hashicorp/terraform',
  'php/php-src',
]);

export const demoIcons = [
  ...demoNpmPackages.map((slug) => ({ type: 'npm' as const, slug })),
  ...demoRepos.map((slug) => ({ type: 'github' as const, slug })),
];
