import Head from 'next/head';
import Image from 'next/image';
import { Repo } from '../components/Repo';
import styles from '../styles/Home.module.css';
import demoRepos from '../demo-repos.json';
import styled from '@emotion/styled';

const Repos = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(70px, 1fr));
  grid-gap: 18px;
  width: 100%;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Repos>
          {demoRepos.map((slug) => (
            <Repo key={slug} slug={slug} />
          ))}
        </Repos>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
