import Head from 'next/head';
import Image from 'next/image';
import { Repo } from '../components/Repo';
import demoRepos from '../demo-repos.json';
import styled from '@emotion/styled';
import { useSession, signIn, signOut } from 'next-auth/react';

const Repos = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(80px, 1fr));
  grid-gap: 18px;
  width: 100%;
`;

export default function Home() {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {session ? (
          <>
            Signed in as {session.user.name} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        ) : (
          <>
            Not signed in <br />
            <button onClick={() => signIn('github')}>Sign in</button>
          </>
        )}
        <Repos>
          {demoRepos.map((slug) => (
            <Repo key={slug} slug={slug} />
          ))}
        </Repos>
      </main>
    </div>
  );
}
