[package]
name = "api"
version = "0.1.0"
authors = ["Sam Denty <sam@samdenty.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
wasm-bindgen = "0.2.70"
wasm-bindgen-futures = "0.4.18"
console_error_panic_hook = "0.1.1"
wee_alloc = "0.4.2"
console_log = "0.2.0"
serde_json = "1.0"
repo_icons = { path = ".." }
log = "0.4.14"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
