account_id = "3abe6f685dab548d1e22cb0f977a9e18"
compatibility_date = "2022-11-30"
main = "build/worker/shim.mjs"
name = "github-icons"
routes = ["github-icons.com/*"]
usage_model = "unbound"
workers_dev = false

[[kv_namespaces]]
binding = "TOKENS"
id = "e6f72a9cfb3340cba8d9a53ddbd77031"

[[r2_buckets]]
binding = "CACHE"
bucket_name = "cache"
preview_bucket_name = "cache"

[build]
command = "cargo install -q worker-build2 && worker-build2 --release && cat src/init.js build/worker/shim.mjs > build/worker/shim2.mjs && mv build/worker/shim2.mjs build/worker/shim.mjs" # required

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
