name = "github-icons"
main = "build/worker/shim.mjs"
workers_dev = false
compatibility_date = "2022-10-09"
account_id = "3abe6f685dab548d1e22cb0f977a9e18"
routes = ["github-icons.com/*"]
usage_model = "unbound"

[[r2_buckets]]
binding = "CACHE"
bucket_name = "cache"


[build]
command = "cargo install -q worker-build2 && worker-build2 --release && cat src/init.js build/worker/shim.mjs > build/worker/shim2.mjs && mv build/worker/shim2.mjs build/worker/shim.mjs" # required

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
