name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: alank976/wrangler-action@support-rust-wasm
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: api
        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
